/**
 * src/lib/types/database.ts
 *
 * This file mirrors what `supabase gen types typescript` would produce
 * for the Luna Labs schema. Once you have a live Supabase project, run:
 *
 *   pnpm supabase gen types typescript \
 *     --project-id YOUR_PROJECT_ID \
 *     > src/lib/types/database.ts
 *
 * and replace this file with the output. The rest of the codebase imports
 * from this file, so that one command updates all types site-wide.
 *
 * HOW TO GET YOUR PROJECT ID:
 *   Supabase dashboard → Settings → General → Reference ID
 */

export type LeadStatus = 'new' | 'contacted' | 'closed';
export type ProjectStatus = 'live' | 'concept' | 'in-progress';

export type ServiceType = 'Web Systems' | 'UI/UX Design' | 'Custom SaaS' | 'Other';

// ── Row types (what you read from the DB) ─────────────────────────────
export interface Lead {
	[key: string]: unknown;
	id: string; // uuid — generated by Supabase
	name: string;
	email: string;
	business: string | null; // optional — some leads are individuals
	service_requested: ServiceType;
	message: string;
	status: LeadStatus;
	created_at: string; // ISO 8601 timestamp string from Postgres
}

export interface Project {
	[key: string]: unknown;
	id: string;
	title: string;
	category: string;
	description: string;
	stack: string[];
	status: ProjectStatus;
	website_url: string | null;
	logo_url: string | null;
	year: string;
	featured: boolean;
	is_published: boolean;
	sort_order: number;
	created_at: string;
	updated_at: string;
}

export interface AllowedAdmin {
	[key: string]: unknown;
	email: string;
	created_at: string;
}

// ── Insert types (what you write to the DB) ───────────────────────────
// Omit server-generated fields — Supabase fills these automatically.
export interface LeadInsert {
	[key: string]: unknown;
	name: string;
	email: string;
	business: string | null;
	service_requested: ServiceType;
	message: string;
}

export interface ProjectInsert {
	[key: string]: unknown;
	id?: string;
	title: string;
	category: string;
	description: string;
	stack: string[];
	status: ProjectStatus;
	website_url: string | null;
	logo_url: string | null;
	year: string;
	featured: boolean;
	is_published: boolean;
	sort_order: number;
	created_at?: string;
	updated_at?: string;
}

// ── Update types (partial — only the fields you want to change) ────────
export interface LeadUpdate {
	[key: string]: unknown;
	status?: LeadStatus;
}

export interface ProjectUpdate {
	[key: string]: unknown;
	title?: string;
	category?: string;
	description?: string;
	stack?: string[];
	status?: ProjectStatus;
	website_url?: string | null;
	logo_url?: string | null;
	year?: string;
	featured?: boolean;
	is_published?: boolean;
	sort_order?: number;
	updated_at?: string;
}

// ── Supabase Database shape (used to type the client) ─────────────────
export interface Database {
	public: {
		Tables: {
			leads: {
				Row: Lead;
				Insert: LeadInsert;
				Update: LeadUpdate;
				Relationships: [];
			};
			projects: {
				Row: Project;
				Insert: ProjectInsert;
				Update: ProjectUpdate;
				Relationships: [];
			};
			allowed_admins: {
				Row: AllowedAdmin;
				Insert: AllowedAdmin;
				Update: Partial<AllowedAdmin>;
				Relationships: [];
			};
		};
		Views: Record<string, never>;
		Functions: Record<string, never>;
		Enums: Record<string, never>;
		CompositeTypes: Record<string, never>;
	};
}
