/**
 * src/lib/types/database.ts
 *
 * This file mirrors what `supabase gen types typescript` would produce
 * for the Luna Labs schema. Once you have a live Supabase project, run:
 *
 *   pnpm supabase gen types typescript \
 *     --project-id YOUR_PROJECT_ID \
 *     > src/lib/types/database.ts
 *
 * and replace this file with the output. The rest of the codebase imports
 * from this file, so that one command updates all types site-wide.
 *
 * HOW TO GET YOUR PROJECT ID:
 *   Supabase dashboard → Settings → General → Reference ID
 */

export type LeadStatus = 'new' | 'contacted' | 'closed';

export type ServiceType =
  | 'Web Systems'
  | 'UI/UX Design'
  | 'Custom SaaS'
  | 'Other';

// ── Row types (what you read from the DB) ─────────────────────────────
export interface Lead {
  id:                string;        // uuid — generated by Supabase
  name:              string;
  email:             string;
  business:          string | null; // optional — some leads are individuals
  service_requested: ServiceType;
  message:           string;
  status:            LeadStatus;
  created_at:        string;        // ISO 8601 timestamp string from Postgres
}

// ── Insert types (what you write to the DB) ───────────────────────────
// Omit server-generated fields — Supabase fills these automatically.
export type LeadInsert = Omit<Lead, 'id' | 'created_at' | 'status'>;

// ── Update types (partial — only the fields you want to change) ────────
export type LeadUpdate = Partial<Pick<Lead, 'status'>>;

// ── Supabase Database shape (used to type the client) ─────────────────
export interface Database {
  public: {
    Tables: {
      leads: {
        Row:    Lead;
        Insert: LeadInsert;
        Update: LeadUpdate;
      };
    };
  };
}